import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/material/ui";
import faqs from "@/data/faqs"
import FAQ from '@/components/FAQ'
import MoreFAQ from '@/components/MoreFAQ';
import Sponsors from '@/components/Sponsors'
import RSVP from '@/components/RSVP'  
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {  
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>{children}</ThemeProvider>
        <FAQ faqs={faqs} />
        <MoreFAQ />
        <Sponsors />
        <RSVP />
        <Footer />
      </body>
    </html>
  );
}
